# (KNN Classifier)--PartB
## Breast cancer wisconsin dataset
In this assignment, we will build a KNN classifier that takes an features as as input and outputs a label 0 or 1.

The breast cancer dataset contains 569 samples with 30 real, positive features (including cancer mass attributes like mean radius, mean texture, mean perimeter, et cetera). Of the samples, 212 are labeled “malignant” and 357 are labeled “benign”. 
You can find more details in: https://scikit-learn.org/stable/datasets/index.html#breast-cancer-dataset

In [1]:
from sklearn.datasets import load_breast_cancer
import numpy as np
## Load the training set
data = load_breast_cancer()
X = data.data
y = data.target


In [2]:
## print some statistics on the dataset
### TODO YOUR CODE ###

# print("Total number of samples: ", )
print ("Total number of samples: ", len(X))

# print the number of features per sample
print('Number of features per sample: ', X.shape[1])

# Total number of classes
print("Total number of classes: ", np.unique(y))

# print the number of samples in each class
print("Number of malignant: ", len(X) - np.count_nonzero(y))
print("Number of benign: ", np.count_nonzero(y))



Total number of samples:  569
Number of features per sample:  30
Total number of classes:  [0 1]
Number of malignant:  212
Number of benign:  357


## Splitting the Train data to Train and Validate Sets

In [3]:
from sklearn.model_selection import train_test_split
### TODO YOUR CODE ###

# Split the data (i.e. features and target) into 70% train, 15% validate, and 15% test; Use Random Seed 777
np.random.seed(777)
trainx, X_rem, trainy, y_rem = train_test_split(X,y, train_size=0.7)
valx, testx, valy, testy = train_test_split(X_rem,y_rem, test_size=0.5)

## Nearest neighbor classification with L2 distance

To compute nearest neighbors in our data set, we need to first be able to compute distances between data points. A natural distance function is _Euclidean distance_: for two vectors $x, y \in \mathbb{R}^d$, their Euclidean distance is defined as 
$$\|x - y\| = \sqrt{\sum_{i=1}^d (x_i - y_i)^2}.$$
Often we omit the square root, and simply compute _squared Euclidean distance_:
$$\|x - y\|^2 = \sum_{i=1}^d (x_i - y_i)^2.$$
For the purposes of nearest neighbor computations, the two are equivalent: for three vectors $x, y, z \in \mathbb{R}^d$, we have $\|x - y\| \leq \|x - z\|$ if and only if $\|x - y\|^2 \leq \|x - z\|^2$.

## 1. Nearest neighbor classification with L2 distance

Write a function, **NN_L2**, which takes as input the training data (`trainx` and `trainy`) and the test points (`evalx`) and predicts labels for these test points using 1-NN classification. These labels should be returned in a `numpy` array with one entry per test point. For **NN_L2**, the L2 norm should be used as the distance metric.

In [4]:
def NN_L2(trainx, trainy, evalx):
    # inputs: trainx, trainy, testx <-- as defined above
    # output: an np.array of the predicted values for testy 
    
    ### START CODE HERE ###
    
    predicty = np.zeros(evalx.shape[0])
    for i in range(evalx.shape[0]):
        distance = []
        for j in range(trainx.shape[0]):
            euclidean_distance = np.linalg.norm(trainx[j] - evalx[i])
            distance.append([euclidean_distance, trainy[j]])
        predicty[i] = sorted(distance)[0][1]
    
    
    return predicty
    ### END CODE HERE ###

## 2. K-Nearest neighbor classification with L2 distance

Write a function, **KNN_L2**, which takes as input the training data (`trainx` and `trainy`), the test points (`evalx`), and the value of **K** (integer) and predicts labels for these test points using K-NN classification. These labels should be returned in a `numpy` array with one entry per test point.

In [21]:
def KNN_L2(trainx, trainy, evalx, K):
    # output: an np.array of the predicted values for testy 
    
    ### START CODE HERE ###
        
    predicty = np.zeros(evalx.shape[0])
    for i in range(evalx.shape[0]):
        distance = []
        for j in range(trainx.shape[0]):
            euclidean_distance = np.linalg.norm(trainx[j] - evalx[i])
            distance.append([euclidean_distance, trainy[j]])
        sorted_distance = sorted(distance)
        predicted_class = 0;
        for val in range(K):
            if sorted_distance[val][1] == 1:
                predicted_class += 1
            else:
                predicted_class -= 1
        
        predicty[i] = 0.0
        if predicted_class >= 0:
            predicty[i] = 1.0
            
    
    return predicty
    ### END CODE HERE ###

In [23]:
KNN_L2(trainx, trainy, testx, 3)

array([0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
       1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1.])

## 3. Nearest neighbor classification with L1 distance

We now compute nearest neighbors using the L1 distance (sometimes called *Manhattan Distance*).

Write a function, **NN_L1**, which again takes as input the arrays `trainx`, `trainy`, and `evalx`, and predicts labels for the test points using 1-nearest neighbor classification. For **NN_L1**, the L1 distance metric should be used. As before, the predicted labels should be returned in a `numpy` array with one entry per test point.

Notice that **NN_L1** and **NN_L2** may well produce different predictions on the test set.

In [25]:
def NN_L1(trainx, trainy, evalx):
    # inputs: trainx, trainy, testx <-- as defined above
    # output: an np.array of the predicted values for testy 
    
    ### START CODE HERE ###
    predicty = np.zeros(evalx.shape[0])
    for i in range(evalx.shape[0]):
        distance = []
        for j in range(trainx.shape[0]):
            euclidean_distance = np.linalg.norm(trainx[j] - evalx[i], 1)
            distance.append([euclidean_distance, trainy[j]])
        predicty[i] = sorted(distance)[0][1]
    
    
    return predicty
    ### END CODE HERE ###

## 4. K-Nearest neighbor classification with L1 distance

Write a function, **KNN_L1**, which takes as input the training data (`trainx` and `trainy`), the test points (`evalx`), and the value of **K** (integer) and predicts labels for these test points using K-NN classification and L1 distance metric. These labels should be returned in a `numpy` array with one entry per test point.

In [27]:
def KNN_L1(trainx, trainy, evalx, K):
    # output: an np.array of the predicted values for testy 
    
    ### START CODE HERE ###
        
    predicty = np.zeros(evalx.shape[0])
    for i in range(evalx.shape[0]):
        distance = []
        for j in range(trainx.shape[0]):
            euclidean_distance = np.linalg.norm(trainx[j] - evalx[i], 1)
            distance.append([euclidean_distance, trainy[j]])
        sorted_distance = sorted(distance)
        predicted_class = 0;
        for val in range(K):
            if sorted_distance[val][1] == 1:
                predicted_class += 1
            else:
                predicted_class -= 1
        
        predicty[i] = 0.0
        if predicted_class >= 0:
            predicty[i] = 1.0
            
    
    return predicty
    ### END CODE HERE ###

## 5. K-Nearest neighbor classifier

Write a function, **KNN**, which takes as input the training data (`trainx` and `trainy`), the test points (`evalx`), the value of **K** (integer), and a parameter for deciding the distance metric to be used (for example 1 for L1 and 2 for L2) and predicts labels for these test points using KNN classification. These labels should be returned in a `numpy` array with one entry per test point.

In [29]:
def KNN(trainx, trainy, evalx, K, dist_metric=2):
    # output: an np.array of the predicted values for testy 
    
    ### START CODE HERE ###
        
    predicty = np.zeros(evalx.shape[0])
    for i in range(evalx.shape[0]):
        distance = []
        for j in range(trainx.shape[0]):
            euclidean_distance = np.linalg.norm(trainx[j] - evalx[i], dist_metric)
            distance.append([euclidean_distance, trainy[j]])
        sorted_distance = sorted(distance)
        predicted_class = 0;
        for val in range(K):
            if sorted_distance[val][1] == 1:
                predicted_class += 1
            else:
                predicted_class -= 1
        
        predicty[i] = 0.0
        if predicted_class >= 0:
            predicty[i] = 1.0
            
    
    return predicty
    ### END CODE HERE ###

## 6. Putting it all together

Write code that allows you to select the hyper-parameters (distance measure and the value of K) by calling the KNN classifier with different values of K and either L1 or L2 distance measure. Make sure that you set the hyper-parameters using the validation set and not the test set. You need to systemtically try different values for K in conjunction with a distance measure and tabulate the results (you can do that be craeting a seperate cell and documenting in that cell) and note down the best hyper-parameter settings.

In [50]:
from sklearn.metrics import accuracy_score
from numpy import unravel_index

In [91]:
### START CODE HERE ###
def val_accuracy(K, L, valx, valy):
    predicty = KNN(trainx, trainy, valx, K, dist_metric=L)
    
#     print('accuracy score for knn with K =', K,' and L',L,' is: ', accuracy_score(valy, predicty))
    return accuracy_score(valy, predicty)

scores = np.array([[0,0,0]])
for i in range(1,25):
    for j in range (1,3):
        x = val_accuracy(i, j, valx, valy)
        scores = np.append(scores, [[i, j, x]],axis=0)
         


print (scores)
max_index = scores.argmax(axis=0)
print('highest score is ', scores[max_index[2]][2], 'at k=', scores[max_index[2]][0], 'and L=', scores[max_index[2]][1])



### END CODE HERE ###

[[ 0.          0.          0.        ]
 [ 1.          1.          0.91764706]
 [ 1.          2.          0.88235294]
 [ 2.          1.          0.89411765]
 [ 2.          2.          0.90588235]
 [ 3.          1.          0.90588235]
 [ 3.          2.          0.92941176]
 [ 4.          1.          0.89411765]
 [ 4.          2.          0.91764706]
 [ 5.          1.          0.90588235]
 [ 5.          2.          0.92941176]
 [ 6.          1.          0.90588235]
 [ 6.          2.          0.92941176]
 [ 7.          1.          0.92941176]
 [ 7.          2.          0.92941176]
 [ 8.          1.          0.92941176]
 [ 8.          2.          0.91764706]
 [ 9.          1.          0.92941176]
 [ 9.          2.          0.91764706]
 [10.          1.          0.90588235]
 [10.          2.          0.91764706]
 [11.          1.          0.90588235]
 [11.          2.          0.91764706]
 [12.          1.          0.90588235]
 [12.          2.          0.90588235]
 [13.          1.        

# 7. Test errors and the confusion matrix

Once the hyper-parameters have been selected, we now would like to perform a final evaluation on the test set and record the error rates. Also, Write a function, **confusion**, which takes as input the true labels for the test set (that is, `testy`) as well as the predicted labels and returns the confusion matrix. The confusion matrix should be a `np.array` of shape `(2,2)`. Also, record the confusion matrix in your assignment report.

**Note:** Record the cpu time it takes to perform the evaluation on the test set using functions like **time.time()**.

In [88]:
import pandas as pd
import time

In [89]:
def confusion(testy, testy_fit):
    # inputs: the correct labels, the fitted KNN labels 
    # output: a 2x2 np.array representing the confusion matrix as above
    
    ### START CODE HERE ###
    
    
    df_confusion = pd.crosstab(testy, testy_fit, rownames=['Actual'], colnames=['Predicted'], margins=True)
    return df_confusion
    ### END CODE HERE ###

In [95]:
# Code for performing the final evaluation on the test set and generating the confuson matrix.
### START CODE HERE ###
start_time = time.time()
predicty = KNN(trainx, trainy, testx, 3, dist_metric=2)
print("--- %s seconds ---" % (time.time() - start_time))
print('Accuracy =',val_accuracy(3, 2, testx, testy))
confusion(testy,predicty)

### END CODE HERE ###

--- 0.20447945594787598 seconds ---
Accuracy = 0.9418604651162791


Predicted  0.0  1.0  All
Actual                  
0           22    4   26
1            1   59   60
All         23   63   86

## 8. Preparing the assignment report

You need to prepare the assignment report and submit your code and report to the Blackboard assignment. You need to record your answers for the following questions in the report:
1. What is the error rate on the validation set for NN_L2?
2. What is the best error rate on the validation set for KNN_L2?
3. What is the error rate on the validation set for NN_L1?
4. What is the best error rate on the validation set for KNN_L1?
5. What is the error rate on the test set?
7. Do you need to normalize data, in general, when using KNN?
8. Do you need to normalize data when using KNN for the given problem? Explain why?

In [104]:
print('1. The error rate on validation set for NN_L2 is ', 1-val_accuracy(1, 2, valx, valy))
print('2. The best error rate on validation set for KNN_L2 is ', 1-val_accuracy(3, 2, valx, valy))
print('3. The error rate on validation set for NN_L1 is ', 1-val_accuracy(1, 1, valx, valy))
print('4. The best error rate on validation set for NN_L1 is ', 1-val_accuracy(8, 1, valx, valy))
print('5. The error rate on test set is ', 1-val_accuracy(3, 2, testx, testy))


1. The error rate on validation set for NN_L2 is  0.11764705882352944
2. The best error rate on validation set for KNN_L2 is  0.07058823529411762
3. The error rate on validation set for NN_L1 is  0.08235294117647063
4. The best error rate on validation set for NN_L1 is  0.07058823529411762
5. The error rate on test set is  0.05813953488372092


## 9. Extra Stuff

You are invited to try some more ideas as extra work like:
1. Implementing weighted KNN where the vote of a neighbour is scaled down based on its distance from the test point.
2. Implement L_infinity distance measure and use it for classification.

## Points to remember

You need to keep in mind the following points:
1. Use numpy arrays and numpy libraries for efficient computations. 
2. Vectorize the code wherever possible instead of using explicit loops. This will significantly speed-up your code.