## C. Neural Network: Regression 
We will modify the architecture that developed in part A to use it for Regression on **Arifoil Self-Noise** Data Set. 

More details on the dataset can be found at: https://archive.ics.uci.edu/ml/datasets/Airfoil+Self-Noise

Attribute Information:

This problem has the following inputs:
1. Frequency, in Hertzs.
2. Angle of attack, in degrees.
3. Chord length, in meters.
4. Free-stream velocity, in meters per second.
5. Suction side displacement thickness, in meters.

The only output is:
6. Scaled sound pressure level, in decibels.

In [76]:
# Package imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
from fast_ml.model_development import train_valid_test_split
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
import matplotlib.pyplot as plt


%matplotlib inline

np.random.seed(777)

In [3]:
df = pd.read_csv("Airfoil.csv", header=None)
df.rename(columns = {0:"Frequency", 1:"Angle_of_attack", 2:"Chord_length", 3:"Free-stream_velocity", 4:"Suction_side_displacement_thickness", 5:"Scaled_sound_pressure_level"},inplace = True)
df.head()

Frequency  Angle_of_attack  Chord_length  Free-stream_velocity  \
0        800              0.0        0.3048                  71.3   
1       1000              0.0        0.3048                  71.3   
2       1250              0.0        0.3048                  71.3   
3       1600              0.0        0.3048                  71.3   
4       2000              0.0        0.3048                  71.3   

   Suction_side_displacement_thickness  Scaled_sound_pressure_level  
0                             0.002663                      126.201  
1                             0.002663                      125.201  
2                             0.002663                      125.951  
3                             0.002663                      127.591  
4                             0.002663                      127.461

In [41]:
Y = df['Scaled_sound_pressure_level']
Y =Y.to_numpy()
Y = Y.reshape((Y.shape[0],1))
Y, Y.shape

(array([[126.201],
        [125.201],
        [125.951],
        ...,
        [106.604],
        [106.224],
        [104.204]]),
 (1503, 1))

In [42]:
X = df.drop(['Scaled_sound_pressure_level'], axis='columns')
X = X.to_numpy()
X , X.shape

(array([[8.00000e+02, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
        [1.00000e+03, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
        [1.25000e+03, 0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
        ...,
        [4.00000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02],
        [5.00000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02],
        [6.30000e+03, 1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02]]),
 (1503, 5))

In [43]:
train_data, X_rem, train_labels, y_rem = train_test_split(X,Y, train_size=0.7)

In [44]:
valid_data, test_data, valid_labels, test_labels = train_test_split(X_rem,y_rem, test_size=0.5)

In [45]:
valid_data

array([[1.25000e+03, 6.70000e+00, 1.01600e-01, 5.55000e+01, 5.21390e-03],
       [3.15000e+03, 0.00000e+00, 1.01600e-01, 7.13000e+01, 1.21072e-03],
       [6.30000e+03, 7.30000e+00, 2.28600e-01, 3.17000e+01, 1.32672e-02],
       ...,
       [3.15000e+03, 4.80000e+00, 2.54000e-02, 5.55000e+01, 8.73218e-04],
       [5.00000e+02, 9.50000e+00, 2.54000e-02, 3.17000e+01, 4.61377e-03],
       [3.15000e+03, 2.22000e+01, 2.54000e-02, 3.96000e+01, 2.29028e-02]])

In [46]:
scaler = preprocessing.StandardScaler().fit(train_data)
train_data = scaler.transform(train_data)
valid_data = scaler.transform(valid_data)
test_data = scaler.transform(test_data)

In [47]:
trainx = train_data.T
trainy = train_labels.T
validx = valid_data.T
validy = valid_labels.T
testx = test_data.T
testy = test_labels.T

In [48]:
trainx.shape, trainy.shape, validx.shape, validy.shape, testx.shape, testy.shape

((5, 1052), (1, 1052), (5, 225), (1, 225), (5, 226), (1, 226))

In [49]:
X = trainx
Y = trainy

In [50]:
### START CODE HERE ###
shape_X = X.shape
shape_Y = Y.shape
m = shape_X[1]  # training set size
### END CODE HERE ###

print ('No. of training samples: ' + str(m))
print ('Number of features per sample: ' + str(shape_X[0]))

No. of training samples: 1052
Number of features per sample: 5


In [51]:
def model_architecture(X, Y):
    """
    Arguments:
    X -- input dataset of shape (input size, number of examples)
    Y -- labels of shape (output size, number of examples)
    
    Returns:
    n_x -- the size of the input layer
    n_h -- the size of the hidden layer
    n_y -- the size of the output layer
    """
    ### START CODE HERE ### 
    n_x = shape_X[0] # size of input layer
    n_h = 10 
    n_y = 1 # size of output layer
    ### END CODE HERE ###
    return (n_x, n_h, n_y)

In [52]:
def initialize_parameters(n_x, n_h, n_y):
    """
    Argument:
    n_x -- size of the input layer
    n_h -- size of the hidden layer
    n_y -- size of the output layer
    
    Returns:
    params -- python dictionary containing your parameters:
                    W1 -- weight matrix of shape (n_h, n_x)
                    b1 -- bias vector of shape (n_h, 1)
                    W2 -- weight matrix of shape (n_y, n_h)
                    b2 -- bias vector of shape (n_y, 1)
    """
    
    np.random.seed(2)

    
    ### START CODE HERE ###
    W1 = np.random.randn(n_h, n_x) * 0.01
    b1 = np.zeros((n_h, 1))
    W2 = np.random.randn(n_y, n_h) * 0.01
    b2 = np.zeros((n_y, 1))
    ### END CODE HERE ###
    
    assert (W1.shape == (n_h, n_x))
    assert (b1.shape == (n_h, 1))
    assert (W2.shape == (n_y, n_h))
    assert (b2.shape == (n_y, 1))
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [53]:
def sigmoid(x):
    ### Update THE CODE HERE ###
    return 1/(1 + np.exp(-x))
    ### END CODE HERE ###

In [54]:
def forward_propagation(X, parameters):
    """
    Argument:
    X -- input data of size (n_x, m)
    parameters -- python dictionary containing your parameters (output of initialization function)
    
    Returns:
    A2 -- The sigmoid output of the second activation
    cache -- a dictionary containing "Z1", "A1", "Z2" and "A2"
    """
    # Retrieve each parameter from the dictionary "parameters"
    ### START CODE HERE ### 
    W1 = parameters.get('W1')
    b1 = parameters.get('b1')
    W2 = parameters.get('W2')
    b2 = parameters.get('b2')
    ### END CODE HERE ###
    
    # Implement Forward Propagation to calculate A2 (probabilities)
    ### START CODE HERE ### 
    Z1 = np.dot(W1, X) + b1 
    A1 = np.tanh(Z1)
#     A1 = relu(Z1)
#     A1 = sigmoid(Z1)
    Z2 = np.dot(W2, A1) + b2
    A2 = Z2
    ### END CODE HERE ###
    

    
    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}
    
    return A2, cache

In [61]:
def compute_cost(A2, Y):
    """
    Arguments:
    A2 -- The sigmoid output of the second activation, of shape (1, number of examples)
    Y -- "true" labels vector of shape (1, number of examples)
       
    Returns:
    loss -- cross-entropy loss given equation (7)
    
    """
    m = Y.shape[0] # number of example
    
    # Compute the RSS cost
    ### START CODE HERE ###
    cost =  (- 1 / 2*m) * np.sum((A2 - Y)**2)
    ### END CODE HERE ###
    
    cost = float(np.squeeze(cost))

    assert(isinstance(cost, float))
    
    return cost

In [62]:
def backprop(parameters, cache, X, Y):
    """
    Arguments:
    parameters -- python dictionary containing our parameters 
    cache -- a dictionary containing "Z1", "A1", "Z2" and "A2".
    X -- input data
    Y -- "true" labels
    
    Returns:
    grads -- python dictionary containing your gradients with respect to different parameters
    """
    m = X.shape[1]
    
    # First, retrieve W1 and W2 from the dictionary "parameters".
    ### START CODE HERE ### 
    W1 = parameters.get('W1')
    W2 = parameters.get('W2')
    ### END CODE HERE ###
        
    # Retrieve also A1 and A2 from dictionary "cache".
    ### START CODE HERE ### 
    A1 = cache.get('A1')
    A2 = cache.get('A2')
    ### END CODE HERE ###
    
    # Backward propagation: calculate dW1, db1, dW2, db2. 
    ### START CODE HERE ### 
    dZ2 = A2 - Y
    dW2 = (1 / m) * np.dot(dZ2, A1.T)
    db2 = (1 / m) * np.sum(dZ2, axis=1, keepdims=True)
    dZ1 = np.dot(W2.T, dZ2) * (1 - np.power(A1, 2))
    dW1 = (1 / m) * np.dot(dZ1, X.T)
    db1 = (1 / m) * np.sum(dZ1, axis=1, keepdims=True)
    ### END CODE HERE ###
    
    grads = {"dW1": dW1,
             "db1": db1,
             "dW2": dW2,
             "db2": db2}
    
    return grads

In [63]:
def update(parameters, grads, learning_rate = 0.01):
    """
    Arguments:
    parameters -- python dictionary containing your parameters 
    grads -- python dictionary containing your gradients 
    learning_rate -- The learning rate
    
    Returns:
    parameters -- python dictionary containing your updated parameters 
    """
    # Retrieve each parameter from the dictionary "parameters"
    ### START CODE HERE ### 
    W1 = parameters.get('W1')
    b1 = parameters.get('b1')
    W2 = parameters.get('W2')
    b2 = parameters.get('b2')
    ### END CODE HERE ###
    
    # Retrieve each gradient from the dictionary "grads"
    ### START CODE HERE ### 
    dW1 = grads.get('dW1')
    db1 = grads.get('db1')
    dW2 = grads.get('dW2')
    db2 = grads.get('db2')
    ## END CODE HERE ###
    
    # Update rule for each parameter
    ### START CODE HERE ### 
    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2
    ### END CODE HERE ###
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [64]:
def NeuralNetwork(X, Y, n_h, num_iterations = 10000, learning_rate = 0.01, print_loss=False):
    """
    Arguments:
    X -- dataset
    Y -- labels 
    n_h -- size of the hidden layer
    num_iterations -- Number of iterations in gradient descent loop
    learning_rate -- The learning rate
    print_loss -- if True, print the loss every 1000 iterations
    
    Returns:
    parameters -- parameters learnt by the model. They can then be used to make predictions.
    """
    
    np.random.seed(3)
    n_x = model_architecture(X, Y)[0]
    n_y = model_architecture(X, Y)[2]
    
    # Initialize parameters
    ### START CODE HERE ### 
    parameters = initialize_parameters(n_x, n_h, n_y)
    ### END CODE HERE ###
    
    # Loop (gradient descent)

    for i in range(0, num_iterations):
         
        ### START CODE HERE ### 
        # Forward propagation. Inputs: "X, parameters". Outputs: "A2, cache".
        A2, cache = forward_propagation(X, parameters)
        
        # loss function. Inputs: "A2, Y, parameters". Outputs: "loss".
        loss = compute_cost(A2, Y)
 
        # Backpropagation. Inputs: "parameters, cache, X, Y". Outputs: "grads".
        grads = backprop(parameters, cache, X, Y)
 
        # Gradient descent parameter update. Inputs: "parameters, grads". Outputs: "parameters".
        parameters =  update(parameters, grads, learning_rate = 0.01)
        
        ### END CODE HERE ###
        
        # Print the loss every 100 iterations
        if print_loss and i % 100 == 0:
            print ("loss after iteration %i: %f" %(i, loss))

    return parameters

In [65]:
def predict(parameters, X):
    """
    Arguments:
    parameters -- python dictionary containing your parameters 
    X -- input data 
    
    Returns
    predictions -- vector of predictions of our model
    """
    
    # Computes probabilities using forward propagation, and classifies to 0/1 using 0.5 as the threshold.
    ### START CODE HERE ### 
    A2, cache = forward_propagation(X, parameters)
    
    predictions = np.argmax(A2, axis = 0)
    ### END CODE HERE ###
    
    return predictions

In [91]:
# Build a model with a n_h-dimensional hidden layer
parameters = NeuralNetwork(X, Y, 100, num_iterations = 10000, learning_rate = 0.1, print_loss=False)

In [107]:
# Print accuracy
predictions = predict(parameters, X)
# predictions = predictions.reshape((predictions.shape[0],1))
print(predictions.shape, Y.shape)
print('MSE = %0.4f '% mean_squared_error(Y.T, predictions))

(1052,) (1, 1052)
MSE = 15637.2029 


In [93]:
# Print accuracy
predictions_validation = predict(parameters, validx)
print('MSE = %0.4f '% mean_squared_error(validy.T, predictions_validation))

MSE = 15586.8524 


In [94]:
# Print accuracy
predictions_test = predict(parameters, testx)
print('MSE = %0.4f '% mean_squared_error(testy.T, predictions_test))

MSE = 15649.8851 
